export {default as Accueil} from "./accueil/accueil"
export {default as CarList} from "./CarList/carList"
export {default as Navbar} from "./accueil/navbar"
export {default as FormBox} from "./accueil/formbox"
export {default as AccueilBody} from "./accueil/accueilbody"
export {default as AgenceList} from "./agencesPage/agencesList"
export {agences} from "./agencesPage/agencesList"
export {default as BrandList} from "./BrandList/brandList"
export {default as ServicesList} from "./ServicesList/servicesList"
export {default as AppointmentForm} from "./Account/AppointmentForm"
export {default as VerticalNavbar} from "./Account/VerticalNavbar"
export {default as Account} from "./Account/Account"
export {default as Profil} from "./Account/Profil"
// export {users} from "./accueil/formbox"
export {default as CarForm} from "./Account/CarForm"